### PR TITLE
Gh-179 Java Code Coverage using JaCoCo

### PR DESCRIPTION
**Pull request by rocky341**
Hi @t92549 
Small update here. PR integrates JaCoCo in to Gaas-Rest. JaCoCo generates a code coverage report. Has also been added to the pipeline.

### CODE REVIEW

**Comment by t92549** [comment]
@rocky341 We use [codecov](https://github.com/gchq/gaffer-tools/blob/cebf2b599d727ae74399fafc6b09e80da1560ff9/.github/workflows/continuous-integration.yaml#L152) in the main repos. Not sure where this will eventually end up and how this might effect the PR, just thought I'd let you know

**Comment by rocky341** [comment]
@t92549 ah okay wasn't aware of that thanks. How would you like to proceed? Sounds like it may be better to integrate codecov in instead of JaCoCo?

**Comment by t92549** [comment]
@rocky341 Well if this moves to gaffer-tools for example then we will have to merge the ci/code scanning here with the one in tools, and the code coverage can be merged then too. However, if it goes into its own repo then we would need to setup codecov for that repo. Honestly, with the weird bugs that codecov has been having recently I am tempted to say for now keep it as JaCoCo and in the future when this moves out of experimental we can update to codecov for consistency. Is there anywhere I can see the report for this PR?

**Comment by rocky341** [comment]
> @rocky341 Well if this moves to gaffer-tools for example then we will have to merge the ci/code scanning here with the one in tools, and the code coverage can be merged then too. However, if it goes into its own repo then we would need to setup codecov for that repo. Honestly, with the weird bugs that codecov has been having recently I am tempted to say for now keep it as JaCoCo and in the future when this moves out of experimental we can update to codecov for consistency. Is there anywhere I can see the report for this PR?

@t92549 
Okay sounds good. Yeah so currently in the pipeline if you go to the Java Code Coverage section it gives you a very high level overview code coverage %. Then if you want to see a detailed report run `mvn -B verify -P coverage` from gaas-rest (or gaffer-as-a-service level)  and then go to `gaas-rest/target/site/jacoco/index.html` to see the detailed report generated.

**Comment by t92549** [comment]
Okay cool. I see `Warning: No files were found with the provided path: target/site/jacoco/. No artifacts will be uploaded.` where it tried to upload the coverage

**Comment by rocky341** [comment]
> Okay cool. I see `Warning: No files were found with the provided path: target/site/jacoco/. No artifacts will be uploaded.` where it tried to upload the coverage

@t92549 Should be fixed now. The at a glance results are in the log coverage section.

**Comment by t92549** [comment]
@rocky341 So this is okay but doesn't compare against the branch that is being merged to for PRs as far as I understand. Could you look into how easy it would be to add codecov? If it is hard to do before this is moved out of experimental then we can wait and just use this.
Also the indentation is weird

**Comment by rocky341** [comment]
@t92549 No I don't think it does. Yeah can take a look into that. I won't make any other changes here till we determine if we can use codecov or if we're going to stick with this for now.

**Comment by rocky341** [comment]
Hi, @t92549 have looked into Codecov as requested. What I understand is that codecov does not do the actual scanning of the files but instead hosts the reports and displays the data. Therefore, have integrated Codecov with JaCoCo with JaCoCo doing the scanning and Codecov hosting the data it finds. 

What are your thoughts on this?

**Comment by rocky341** [comment]
@t92549 
Have also included a OWASP dependency checker into the pipeline / mvn clean install for this PR too.

**Comment by t92549** [comment]
> Hi, @t92549 have looked into Codecov as requested. What I understand is that codecov does not do the actual scanning of the files but instead hosts the reports and displays the data. Therefore, have integrated Codecov with JaCoCo with JaCoCo doing the scanning and Codecov hosting the data it finds.
> 
> What are your thoughts on this?

This all looks good! Our main repos use a maven code coverage tool that isn't JaCoCo. I am wondering if we should perhaps change this repo to match them, or, if JaCoCo is more up to date and has more features, swap those repos to this. Do you have any thoughts?
Also are there any other changes or are you ready for this to be merged?

**Comment by rocky341** [comment]
> > Hi, @t92549 have looked into Codecov as requested. What I understand is that codecov does not do the actual scanning of the files but instead hosts the reports and displays the data. Therefore, have integrated Codecov with JaCoCo with JaCoCo doing the scanning and Codecov hosting the data it finds.
> > What are your thoughts on this?
> 
> This all looks good! Our main repos use a maven code coverage tool that isn't JaCoCo. I am wondering if we should perhaps change this repo to match them, or, if JaCoCo is more up to date and has more features, swap those repos to this. Do you have any thoughts? Also are there any other changes or are you ready for this to be merged?

Thanks. Which maven code coverage tool do the other repos use? JaCoCo seems to be pretty good from what I've seen and used although can compare it to the one in the other repos. 
Aside from that the PR is ready to be merged

**Comment by rocky341** [comment]
@t92549 
Actually wait a moment before merging going to simplify the pipeline process

**Comment by rocky341** [comment]
@t92549 
Have simplified the pipeline.
Ready for merging

**Comment by t92549** [comment]
> > > Hi, @t92549 have looked into Codecov as requested. What I understand is that codecov does not do the actual scanning of the files but instead hosts the reports and displays the data. Therefore, have integrated Codecov with JaCoCo with JaCoCo doing the scanning and Codecov hosting the data it finds.
> > > What are your thoughts on this?
> > 
> > 
> > This all looks good! Our main repos use a maven code coverage tool that isn't JaCoCo. I am wondering if we should perhaps change this repo to match them, or, if JaCoCo is more up to date and has more features, swap those repos to this. Do you have any thoughts? Also are there any other changes or are you ready for this to be merged?
> 
> Thanks. Which maven code coverage tool do the other repos use? JaCoCo seems to be pretty good from what I've seen and used although can compare it to the one in the other repos. Aside from that the PR is ready to be merged

https://github.com/gchq/Gaffer/blob/4ff1bbd42e646e5df974a6dfebdca21c4f80cb48/pom.xml#L1267
Seems like it actually does use JaCoCo.
Is this similar-ish to how you are using it? If there are any major differences then maybe we should make them the same but if not I am happy to merge

**Comment by rocky341** [comment]
> > > > Hi, @t92549 have looked into Codecov as requested. What I understand is that codecov does not do the actual scanning of the files but instead hosts the reports and displays the data. Therefore, have integrated Codecov with JaCoCo with JaCoCo doing the scanning and Codecov hosting the data it finds.
> > > > What are your thoughts on this?
> > > 
> > > 
> > > This all looks good! Our main repos use a maven code coverage tool that isn't JaCoCo. I am wondering if we should perhaps change this repo to match them, or, if JaCoCo is more up to date and has more features, swap those repos to this. Do you have any thoughts? Also are there any other changes or are you ready for this to be merged?
> > 
> > 
> > Thanks. Which maven code coverage tool do the other repos use? JaCoCo seems to be pretty good from what I've seen and used although can compare it to the one in the other repos. Aside from that the PR is ready to be merged
> 
> https://github.com/gchq/Gaffer/blob/4ff1bbd42e646e5df974a6dfebdca21c4f80cb48/pom.xml#L1267 Seems like it actually does use JaCoCo. Is this similar-ish to how you are using it? If there are any major differences then maybe we should make them the same but if not I am happy to merge

Yes that does look very similar. It is the exact same plugin being used for JaCoCo and it is also in the same profile `coverage` so I would say the implementation is very similar if not exactly the same.

**Comment by t92549** [comment]
Ready to approve, sorry one last question, was just wondering why the ci workflow is gone?

**Comment by K-itKat20** [comment]
> Ready to approve, sorry one last question, was just wondering why the ci workflow is gone?

The CodeAnalysis.yml included all the steps in the CI.yml so we removed it as its essentially a duplicate.

**Comment by t92549** [comment]
> > Ready to approve, sorry one last question, was just wondering why the ci workflow is gone?
> 
> The CodeAnalysis.yml included all the steps in the CI.yml so we removed it as its essentially a duplicate.

Makes sense, not to be really nitpicky but maybe can the workflow be called like ci and analysis or something just to be ultra clear. Sorry I have had so many small suggestions and questions

**Comment by rocky341** [comment]
> > > Ready to approve, sorry one last question, was just wondering why the ci workflow is gone?
> > 
> > 
> > The CodeAnalysis.yml included all the steps in the CI.yml so we removed it as its essentially a duplicate.
> 
> Makes sense, not to be really nitpicky but maybe can the workflow be called like ci and analysis or something just to be ultra clear. Sorry I have had so many small suggestions and questions

@t92549 
No worries would rather these changes are addressed in the PR as opposed to having to go in and change things after merging. I have renamed the workflow to `CodeAnalysisAndCI` as I think its easier to read than `CIAndCodeAnalysis`

**Review by t92549 — APPROVED** [review]

**Comment by t92549** [comment]
@rocky341 Thanks for all that! Ready to merge if you are

**Comment by rocky341** [comment]
> @rocky341 Thanks for all that! Ready to merge if you are

No problem :D Yes ready to merge please

**Pull request merged**
