### PR TITLE
Kai UI -> gaas-ui

### PR DESCRIPTION
**Pull request by macenturalxl1**
Pulled in Kai `ui/` directory in to `gaffer-experimental/gaas-ui/`

### CODE REVIEW

**Comment by macenturalxl1** [comment]
Hi let me know any thoughts on the UI, or if you want to merge this after the initial `gaas-rest` pull request merger

**Comment by macenturalxl1** [comment]
This Pull Request satisfies both tickets: Decoupling UI from AWS https://github.com/gchq/gaffer-experimental/issues/21 & developing a helmchart for UI to deploy to Kubernetes https://github.com/gchq/gaffer-experimental/issues/18

**Comment by t92549** [comment]
Overall I think that there are just a few small things that can be cleaned up before this is merged:
- `middleware.js` returns the wrong status code when deleting a graph
- `README.md` gives incorrect instructions on how to run the app and middleware together
- There are some eslint warnings that can be cleaned up like unused variables and variables used before defined
- Some formatting and double/single quote inconsistency that would be nice to clean up

There are quite small changes that would just clean up the code and make it easier to read / get running

**Comment by macenturalxl1** [comment]
Hi @t92549, thanks for the review

- fixed the middleware to.js to return the same HTTP Status as the GaaS API would, also the UI will handle any 200 responses as being a successful deletion 
- The README.md has been updated how to run the UI in dev mode using `npm run start` and the various ways developers can customise their dev mode set up
- The 'simple' lint fixes have been resolved, there is the "React was used before defined" lint error that I will fix for the Issue https://github.com/gchq/gaffer-experimental/issues/56, seems to be just a React/lint thing
- Uses single quotes as standard across app

**Review by t92549 — APPROVED** [review]

**Pull request merged**
