### PR TITLE
Gh 292 gaas UI dynamic

### PR DESCRIPTION
**Pull request by rocky341**
Hi @t92549 @GCHQDeveloper314 

This PR introduces the dynamic UI. This means that no additional configuration is required when using different sidecars. The UI is dynamic based on the response it receives from the /what-auth endpoint which is found in the sidecars.

#292

### CODE REVIEW

**Comment by rocky341** [comment]
> I'm seeing "GitHub Actions run-ui-code-analysis" warnings in:
> 
> * `gaas-ui/src/components/login/dynamic-login-form.tsx`
> * `gaas-ui/src/components/navigation-bar/navigation-appbar.tsx`
> * `gaas-ui/src/rest/clients/auth-sidecar-client.ts`

A separate PR is being raised which addresses warnings/does other UI clean up so this should be resolved in that PR

**Comment by rocky341** [comment]
PR



> > I'm seeing "GitHub Actions run-ui-code-analysis" warnings in:
> > 
> > * `gaas-ui/src/components/login/dynamic-login-form.tsx`
> > * `gaas-ui/src/components/navigation-bar/navigation-appbar.tsx`
> > * `gaas-ui/src/rest/clients/auth-sidecar-client.ts`
> 
> A separate PR is being raised which addresses warnings/does other UI clean up so this should be resolved in that PR

PR is #313

**Review by GCHQDeveloper314 — APPROVED** [review]
Comments have been addressed in another issue/PR

**Review by t92549 — COMMENTED** [review]
Looks good aside from the warnings

**Comment by t92549** [comment]
> Looks good aside from the warnings

Never mind

**Comment by t92549** [comment]
Sorry, merging https://github.com/gchq/gaffer-experimental/pull/304 broke this

**Comment by rocky341** [comment]
@t92549 
@GCHQDeveloper314 

Conflicts have been resolved

**Pull request merged**
